fix(dev-env/basic): building and running development
pedronauck/docz pull request #1646
Opened 2021-07-26 13:52 UTC by renatobenks

### Description

The development environment, aka `dev-env/basic`, is not properly working, currently because of a build problem.

### Review

- [ ] Check the copy
- [ ] ...
- [ ] ...

### Pre-merge checklist

- [ ] ...
- [ ] ...

### Screenshots

| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/51369951/126999590-e70d46df-cac8-4653-86ce-36cf1218146d.png) | <img width="1680" alt="Screen Shot 2021-07-26 at 10 46 31" src="https://user-images.githubusercontent.com/51369951/126999557-e2cd5b59-f372-4d04-87bb-840d42d2e1ca.png"> |

2021-07-29 21:56 UTC, pedronauck commented on dev-env/basic/package.json
> +    "docz": "../../core/docz",
💯

2021-07-29 22:03 UTC, pedronauck requested changes
This happened here when I tried to run `yarn dev` inside `dev-env/basic` and check `localhost:3000`

![Screen Shot 2021-07-29 at 19 00 48](https://user-images.githubusercontent.com/2029172/127571526-687dd4fb-1212-4828-922e-824b0c28755c.png)

2021-07-30 13:21 UTC, renatobenks commented
I'm checking it! Thank you for testing it

2021-07-30 16:25 UTC, renatobenks commented
@pedronauck I just checked everything around by setting this up from scratch and it seems to be working fine now. Can you try it again, but this time from a clean setup?

Let me know how it works then.

2021-08-02 20:06 UTC, merged