[WIP] Vue Support
pedronauck/docz pull request #50
Opened 2018-06-16 12:00 UTC by marceloavf

### Description

Initial implementation of a plugin that integrates support for Vue componentes into Docz

### Impediments / Research

#### [react-vue-loader](https://github.com/SmallComfort/react-vue-loader)
- Would be the greatest option, since it's just integrate inside webpack configuration, problems:
   - Doesn't support webpack 4: https://github.com/SmallComfort/react-vue-loader/issues/7

#### [vuera](https://github.com/akxcv/vuera)
- Another great option, just need to include babel configuration for the fastest implementation, problems:
  - Docz don't seems to be understand the babel configuration for `vuera/babel`

### Review

- [ ] Code implementation

### Pre-merge checklist

- [ ] Need to build `examples/vue` folder

---

***Warning:** this is a working in progress*

---

2018-06-16 13:55 UTC, pedronauck commented
@marceloavf you need to transpile the plugin, import on `doczrc.js` and use it, like that:

```js
import { vue } from 'docz-plugin-vue'

export default {
  plugins: [vue()],
}
```

2018-06-16 14:19 UTC, marceloavf commented
It's now building with some console errors:

```shell
Uncaught TypeError: Cannot read property 'constructor' of undefined
    at isReactComponent (vuera.cjs.js?ea64:410)
    at babelReactResolver$$1 (vuera.cjs.js?ea64:475)
    at ProxyComponent.render (root.jsx?1914:29)
    at ProxyComponent.hotComponentRender (react-hot-loader.development.js?ba54:622)
    at ProxyComponent.proxiedRender (react-hot-loader.development.js?ba54:630)
    at finishClassComponent (react-dom.development.js?6df8:13085)
    at updateClassComponent (react-dom.development.js?6df8:13047)
    at beginWork (react-dom.development.js?6df8:13715)
    at performUnitOfWork (react-dom.development.js?6df8:15741)
    at workLoop (react-dom.development.js?6df8:15780)
```
```shell
The above error occurred in the <Root> component:
    in Root (created by HotExportedRoot)
    in AppContainer (created by HotExportedRoot)
    in HotExportedRoot

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

2018-06-20 16:22 UTC, marceloavf commented
Seems to be something with `react-hot-loader`, I'll do some deep debug in it and research in community

2018-06-20 16:28 UTC, pedronauck requested changes

2018-06-20 16:28 UTC, pedronauck commented on packages/docz-plugin-vue/src/index.ts
> +    }) as ModifyBabelRC,
I think that ts will infer this for you... you really need this `as <Something>`?

2018-06-20 16:28 UTC, pedronauck commented on packages/docz-plugin-vue/src/index.ts
> +        test: /\.vue$/,
Try to put some `exclude` and `include` paths here, I think that you that you can prevent some parses!

2018-06-22 11:08 UTC, marceloavf commented
The plugin seems to be compiling with some warning, need to investigate.

2018-06-27 01:18 UTC, closed without merging