rename plugin export to babel6
pedronauck/docz pull request #60
Opened 2018-06-19 11:15 UTC by Swapnull

### Description

Add here a description about your Pull Request

The README for docz-plugin-babel6 currently wont work. 

It currently says
```javascript
import { babel } from 'docz-plugin-babel6'
export default { plugins[babel6()] };
```
But this will result in 'babel6 is not defined' 

In this PR I have changed the export name from the plugin to be babel6 as this makes most sense to me. 
It would be safer, but may make less sense, to just update the README to either

- change the import to `import { babel as babel6 }`
- keep the current import and do `plugins[babel()]`, which is less descriptive. 

### Review

- [ ] Test out the new plugin

2018-06-19 14:08 UTC, pedronauck commented
the plugin export a variable called `babel` @Swapnull, just change it, please 🙏

2018-06-19 17:38 UTC, pedronauck commented
sorry @Swapnull, maybe I didn't be so clear... but I had asked you to change to the correct value exported. Change the exported value now I'll result in a break change version, so I think that is better keep the value exported as `babel`. So, just change on readme to be correct, please :pray:

2018-06-19 17:44 UTC, pedronauck requested changes

2018-06-19 17:44 UTC, pedronauck commented on packages/docz-plugin-babel6/src/index.ts
> -export const babel = () =>
please keep as `babel` 🙏

2018-06-19 17:44 UTC, pedronauck commented on packages/docz-plugin-babel6/README.md
> -import { babel } from 'docz-plugin-babel6'
keep this as `babel` too ✌️

2018-06-19 21:58 UTC, Swapnull commented
@pedronauck I have changed it back to exporting `babel` and updated the readme 😄

2018-06-20 13:25 UTC, pedronauck approved these changes

2018-06-20 13:25 UTC, merged